Add more specific details around normalised PyPI package naming per PEP 503
package-url/purl-spec pull request #165
Opened 2022-04-27 10:25 UTC by westonsteimel

[PEP 503](https://peps.python.org/pep-0503/#normalized-names) specifies more detail around normalised PyPI package naming,
so referencing that and reflecting the wording from it for the PyPI package-url type.

Signed-off-by: Weston Steimel <weston.steimel@anchore.com>

2025-03-04 01:01 UTC, jkowalleck commented
see https://packaging.python.org/en/latest/specifications/name-normalization/

History

    September 2015: The specification of name normalized was approved through [503](https://peps.python.org/pep-0503/#normalized-names).

    November 2015: The specification of valid names was approved through [508](https://peps.python.org/pep-0508/#names).

2025-03-20 08:55 UTC, jkowalleck approved these changes

2025-03-28 13:58 UTC, mprpic submitted a review, later dismissed

2025-03-28 18:12 UTC, jkowalleck commented
@westonsteimel could you resolve the conflicts?

2025-03-31 15:43 UTC, matt-phylum requested changes
This PR is missing a test.

I have one in the duplicate PR I created in an attempt to get this fixed: #262

2025-03-31 15:43 UTC, matt-phylum commented on PURL-TYPES.rst
> +  lowercased with all runs of the characters ``.``, ``-``, or ``_`` replaced with a single ``-`` character.
The correct document is https://packaging.python.org/en/latest/specifications/name-normalization/, not the PEP.

2025-03-31 16:13 UTC, closed without merging

2025-03-31 16:13 UTC, westonsteimel commented
Just use https://github.com/package-url/purl-spec/pull/262