Add rpmmod package type
package-url/purl-spec pull request #199
Opened 2022-10-28 13:09 UTC by mprpic

RPM modules are a concept in the RHEL/Fedora/CentOS land that allow for grouping of arbitrary RPMs. These modules have their own naming scheme and can be identified using their own purl type. The proposal here is to call that type `rpmmod`.

More about RPM modules can be found in either of these sources:

- https://docs.fedoraproject.org/en-US/modularity/using-modules/
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/introduction-to-modules_using-appstream#module-streams_introduction-to-modules
- https://docs.centos.org/en-US/8-docs/managing-userspace-components/assembly_introduction-to-modules/

More about the naming convenstion for RPM modules can also be found here:

https://docs.fedoraproject.org/en-US/modularity/core-concepts/nsvca/#_nsvca_definition

An example of an the NodeJS 14 module on Fedora 36:

```bash
$ cat /etc/redhat-release
Fedora release 36 (Thirty Six)
$ dnf module --repo=fedora-modular info nodejs:14
Name             : nodejs
Stream           : 14
Version          : 3620220301144317
Context          : 5e5ad4a0
Architecture     : x86_64
Profiles         : common [d], development, minimal
Default profiles : common
Repo             : fedora-modular
Summary          : Javascript runtime
Description      : Node.js is a platform built on Chrome''s JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
Requires         : platform:[f36]
Artifacts        : c-ares-0:1.17.2-2.module_f36+13930+82e25793.src
                 : c-ares-0:1.17.2-2.module_f36+13930+82e25793.x86_64
                 : c-ares-debuginfo-0:1.17.2-2.module_f36+13930+82e25793.x86_64
                 [...list truncated...]
```

2022-10-30 15:01 UTC, pombredanne submitted a review, later dismissed
Looking good. Thanks!
Is there a way to find installed modules on a Fedora system?

2022-10-31 12:42 UTC, mprpic commented
> Is there a way to find installed modules on a Fedora system?

There is! `dnf module list --installed`. Alternatively, running just `dnf module list` will list all available module and tag them with `[d]efault, [e]nabled, [x]disabled, [i]nstalled`.

2022-11-15 15:47 UTC, iamwillbar requested changes

2022-11-15 15:47 UTC, iamwillbar commented on PURL-TYPES.rst
> +- The ``version`` is the combined stream, version, and context of an RPM module,
You should call out that the colon needs to be escaped.

2023-02-07 15:18 UTC, mprpic commented
@iamwillbar @pombredanne Is there anything else blocking the merge of this change?

2023-10-03 15:12 UTC, mrizzi commented
Hi, what is the situation with this review? Could this be merged please?

2024-01-16 15:48 UTC, mprpic commented
Any update on merging this PR?

2025-05-20 14:39 UTC, mprpic commented
Closing this because we've decided to use qualifiers on the `rpm` type itself to add information about RPM modules.

If there is a use case in the future that would require RPM modules to be their own entities, we can re-open this.

2025-05-20 14:39 UTC, closed without merging

2025-05-21 10:16 UTC, pombredanne commented
> Closing this because we've decided to use qualifiers on the rpm type itself to add information about RPM modules.

this makes sense.