Add `luarocks` package type
package-url/purl-spec pull request #205
Opened 2022-12-02 18:03 UTC by hishamhm

Hi, I am the lead mantainer of the [LuaRocks](https://luarocks.org) package manager and we'd like to add its entry to the `purl` spec. Thanks!

2024-04-15 17:39 UTC, stevespringett requested changes

2024-04-15 17:39 UTC, stevespringett commented on PURL-TYPES.rst
> +- ``namespace``: The user manifest under which the package is registered. If not given, the root manifest is assumed.
Is the namespace case sensitive or insensitive? Please specify which.

2024-04-15 17:39 UTC, stevespringett commented on PURL-TYPES.rst
> +- ``name``: The LuaRocks package name.
Is the name case sensitive or insensitive? Please specify which.

2024-04-15 17:39 UTC, stevespringett commented on PURL-TYPES.rst
> +- ``version``: The full LuaRocks package version, including module version and rockspec revision.
Is the version case sensitive or insensitive? Please specify which. Additionally, is the version required?

2024-04-17 15:25 UTC, hishamhm commented
@stevespringett Added all the requested clarifications!

2024-04-17 16:06 UTC, merged