docs: consistent naming of the `checksum` qualifier key
package-url/purl-spec pull request #209
Opened 2022-12-10 19:20 UTC by williamboman

This confused me a bit as the spec includes to different variants of this
qualifier: (`checksum` and `checksums`). From reading the spec I believe the
intended variant is `checksum`; this PR consolidates all references to this
qualifier.

2024-11-20 00:09 UTC, johnmhoran commented on PURL-SPECIFICATION.rst
>        a list of `checksums`
@williamboman One question: on line 381, should `checksums` be changed to remove the backticks, as you did on line 324?

2024-11-21 17:59 UTC, pombredanne commented on PURL-SPECIFICATION.rst
>        a list of `checksums`
```suggestion
      a list of checksums
```

2024-11-21 18:14 UTC, pombredanne requested changes
We have a problem here as I messed things up by specifying both "checksum" (singular) and "checksums" (plural) as keys for this qualifier originally. 

We need to recover from this before pushing further changes.
1. We need to survey what the PURL libraries and SBOM docs do today to assess the damage
2. We should decide on the path of least resistance, and least damage with either plural or singular
3. We should update the spec then, but also mentioning the legacy form so that tools authors can accept and fix either plural to singular or singular to plural

2024-11-21 18:16 UTC, pombredanne commented
And also update to use proper Rst with double backticks as in the latest main, as fixed by @andrewpollock

2024-11-21 20:51 UTC, johnmhoran commented
Hi @williamboman  .  Thank you for your PR.  When you have the chance, could you please resolve the conflicts referred to below?

2025-07-01 17:41 UTC, pombredanne commented
- Most implementations do not have specific ode for parsing checksum-related qualifiers
- @matt-phylum in Rust and @jdalton in JS as well as the PHP implementation are using `checksum` singular. Same for Kotlin.
- @matt Ruby uses plural https://github.com/package-url/packageurl-ruby
- @giterlizzi Perl uses plural https://github.com/giterlizzi/perl-URI-PackageURL

Therefore I am inclined to go singular and help Ruby and Perl authors to adopt the singular form.

We should also provide suggestions to also accept plural form for lenient parsing in the FAQ.

2025-07-01 17:41 UTC, pombredanne approved these changes
Let's merge this!

2025-07-01 17:43 UTC, merged