pypi: change default repository
package-url/purl-spec pull request #250
Opened 2023-10-02 14:06 UTC by schischi

`python.pypi.org` is the legacy index domain name and was replaced by `pypi.org` in 2017. See: https://packaging.python.org/en/latest/glossary/#term-pypi.org

2023-10-05 21:29 UTC, sethmlarson approved these changes

2023-10-19 17:34 UTC, woodruffw approved these changes

2023-10-20 10:16 UTC, pombredanne commented
@schischi Thanks... this makes perfect sense. We may want to keep a short note about the previous URL so folks are not confused.

2023-10-20 10:17 UTC, pombredanne requested changes
Here is a simple suggestion

2023-10-20 10:17 UTC, pombredanne commented on PURL-TYPES.rst
> +- The default repository is ``https://pypi.org``.
```suggestion
- The default repository is ``https://pypi.org``. (Previously  ``https://pypi.python.org``.)
```

2023-10-20 13:51 UTC, merged

2023-11-09 16:25 UTC, criminosis commented
@pombredanne out of curiosity does this have any implications for purl equality?

Given a purl `pkg:pypi/Django@4.2.7` and the prior implicit default of `https://pypi.python.org`.

Was it intended for `pkg:pypi/Django@4.2.7` and `pkg:pypi/Django@4.2.7?repository_url=https://pypi.python.org` to be "equal" purls?

Now that it's `https://pypi.org` are there now 3 cases that are intended to be canonically equal to maintain backwards compatibility with "old" purls?
-  `pkg:pypi/Django@4.2.7`(No `repository_url` so implied default)
- `pkg:pypi/Django@4.2.7?repository_url=https://pypi.python.org`
- `pkg:pypi/Django@4.2.7?repository_url=https://pypi.org`